services:
  user_go:
    build:
      context: .
      dockerfile: ./cmd/user/Dockerfile
    ports:
      - "8001:8001"
      - "8082:8082"
    image: user-go-image
    container_name: user_go
    restart: unless-stopped
    volumes:
      - ./files:/app/files
    networks:
      - app-network
    depends_on:
      - pg_db
      - redis_service
      - go_back

  go_back:
    build:
      context: .
      dockerfile: ./cmd/main/Dockerfile
    ports:
      - "8000:8000"
    image: back-go-image
    container_name: back_go
    restart: unless-stopped
    volumes:
      - ./files:/app/files
    networks:
      - app-network
    depends_on:
      - pg_db
      - redis_service

  pg_db:
    image: postgres:16.4
    ports:
      - "54320:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./assets/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data/
    container_name: pg_db
    restart: unless-stopped
    networks:
      - app-network

  redis_service:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    container_name: redis_service
    restart: unless-stopped
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    #      - '--web.external-url=prometheus'

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "8008:3000"

volumes:
  pg_data:
  redis_data:
  go_back:
  prometheus:
  grafana:
  prometheus_data:

networks:
  app-network:
    driver: bridge