global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user_go'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'user_go:8081' ]

  - job_name: 'main_go'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'main_go:8080' ]