global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user_go'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'user_go:8081' ]

  - job_name: 'main_go'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'main_go:8080' ]

  - job_name: 'rating_updater_go'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'rating_updater_go:8084' ]

  - job_name: 'profile_go'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'profile_go:8083' ]

  - job_name: 'wishlists_go'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'wishlists_go:8086' ]