package db

// Инициализация продуктов в базе данных
var productDB = ProductDB{
	products: map[string]Product{
		"1": {
			CurrentPrice:     "1999",
			OldPrice:         "2999",
			Discount:         "33",
			Description:      "Быстрая зарядка Type C, блок питания.",
			ShortDescription: "Быстрая зарядка Type C, блок питания.",
			URL:              "/catalog/product/1",
			Currency:         "$",
		},
		"2": {
			CurrentPrice:     "4999",
			Description:      "Наушники с Bluetooth 5.0, шумоподавлением и кейсом для зарядки.",
			ShortDescription: "Наушники с Bluetooth 5.0, шумоподавлением.",
			Image:            "https://loremflickr.com/320/240?lock=1",
			URL:              "/catalog/product/2",
			Currency:         "$",
		},
		"3": {
			CurrentPrice:     "15999",
			Description:      "Смартфон с дисплеем 6.5 дюймов и 128 ГБ памяти.",
			ShortDescription: "Смартфон 6.5 дюймов, 128 ГБ памяти.",
			Image:            "https://loremflickr.com/320/240?lock=2",
			URL:              "/catalog/product/3",
			Currency:         "$",
		},
		"4": {
			CurrentPrice:     "7999",
			Description:      "Игровая клавиатура с RGB подсветкой и механическими переключателями.",
			ShortDescription: "Игровая клавиатура с RGB подсветкой.",
			Image:            "https://loremflickr.com/320/240?lock=3",
			URL:              "/catalog/product/4",
			Currency:         "$",
		},
		"5": {
			CurrentPrice:     "2999",
			OldPrice:         "3999",
			Discount:         "25",
			Description:      "Беспроводная мышь с оптическим сенсором и настраиваемыми кнопками.",
			ShortDescription: "Беспроводная мышь с оптическим сенсором.",
			Image:            "https://loremflickr.com/320/240?lock=4",
			URL:              "/catalog/product/5",
			Currency:         "$",
		},
		"6": {
			CurrentPrice:     "12999",
			Description:      "Смарт-часы с датчиком сердечного ритма и GPS.",
			ShortDescription: "Смарт-часы с датчиком сердечного ритма.",
			Image:            "https://loremflickr.com/320/240?lock=5",
			URL:              "/catalog/product/6",
			Currency:         "$",
		},
		"7": {
			CurrentPrice:     "999",
			Description:      "Кабель для зарядки USB-C длиной 1.5 метра.",
			ShortDescription: "Кабель для зарядки USB-C, 1.5 метра.",
			Image:            "https://loremflickr.com/320/240?lock=6",
			URL:              "/catalog/product/7",
			Currency:         "$",
		},
		"8": {
			CurrentPrice:     "14999",
			Description:      "Планшет с экраном 10 дюймов и поддержкой стилуса.",
			ShortDescription: "Планшет 10 дюймов, поддержка стилуса.",
			Image:            "https://loremflickr.com/320/240?lock=7",
			URL:              "/catalog/product/8",
			Currency:         "$",
		},
		"9": {
			CurrentPrice:     "19999",
			OldPrice:         "24999",
			Discount:         "20",
			Description:      "Ноутбук с процессором i7 и SSD на 512 ГБ.",
			ShortDescription: "Ноутбук i7, SSD 512 ГБ.",
			Image:            "https://loremflickr.com/320/240?lock=8",
			URL:              "/catalog/product/9",
			Currency:         "$",
		},
		"10": {
			CurrentPrice:     "799",
			Description:      "Чехол для смартфона из мягкого силикона.",
			ShortDescription: "Чехол для смартфона, силикон.",
			Image:            "https://loremflickr.com/320/240?lock=9",
			URL:              "/catalog/product/10",
			Currency:         "$",
		},
		"11": {
			CurrentPrice:     "11999",
			Description:      "Зеркальная камера с разрешением 24 МП и объективом 18-55 мм.",
			ShortDescription: "Зеркальная камера 24 МП.",
			Image:            "https://loremflickr.com/320/240?lock=10",
			URL:              "/catalog/product/11",
			Currency:         "$",
		},
		"12": {
			CurrentPrice:     "2999",
			Description:      "Портативный Bluetooth-динамик с водонепроницаемым корпусом.",
			ShortDescription: "Bluetooth-динамик, водонепроницаемый.",
			Image:            "https://loremflickr.com/320/240?lock=11",
			URL:              "/catalog/product/12",
			Currency:         "$",
		},
		"13": {
			CurrentPrice:     "49999",
			Description:      "Игровая консоль с поддержкой 4K и встроенным SSD.",
			ShortDescription: "Игровая консоль, 4K, SSD.",
			Image:            "https://loremflickr.com/320/240?lock=12",
			URL:              "/catalog/product/13",
			Currency:         "$",
		},
		"14": {
			CurrentPrice:     "1199",
			Description:      "Микрофон для записи подкастов и стримов.",
			ShortDescription: "Микрофон для подкастов и стримов.",
			Image:            "https://loremflickr.com/320/240?lock=13",
			URL:              "/catalog/product/14",
			Currency:         "$",
		},
		"15": {
			CurrentPrice:     "3499",
			Description:      "Геймпад с поддержкой Bluetooth для ПК и консолей.",
			ShortDescription: "Геймпад Bluetooth для ПК и консолей.",
			Image:            "https://loremflickr.com/320/240?lock=14",
			URL:              "/catalog/product/15",
			Currency:         "$",
		},
		"16": {
			CurrentPrice:     "2299",
			Description:      "Внешний аккумулятор на 10000 мАч с быстрой зарядкой.",
			ShortDescription: "Внешний аккумулятор 10000 мАч.",
			Image:            "https://loremflickr.com/320/240?lock=15",
			URL:              "/catalog/product/16",
			Currency:         "$",
		},
		"17": {
			CurrentPrice:     "19999",
			Description:      "Проектор для домашнего кинотеатра с поддержкой Full HD.",
			ShortDescription: "Проектор для кинотеатра, Full HD.",
			Image:            "https://loremflickr.com/320/240?lock=16",
			URL:              "/catalog/product/17",
			Currency:         "$",
		},
		"18": {
			CurrentPrice:     "34999",
			Description:      "Графический планшет с 8192 уровнями нажатия и стилусом.",
			ShortDescription: "Графический планшет со стилусом.",
			Image:            "https://loremflickr.com/320/240?lock=17",
			URL:              "/catalog/product/18",
			Currency:         "$",
		},
		"19": {
			CurrentPrice:     "9999",
			Description:      "Очки виртуальной реальности с поддержкой 4K.",
			ShortDescription: "Очки виртуальной реальности 4K.",
			Image:            "https://loremflickr.com/320/240?lock=18",
			URL:              "/catalog/product/19",
			Currency:         "$",
		},
		"20": {
			CurrentPrice:     "7499",
			Description:      "Видеорегистратор с ночной съемкой и GPS.",
			ShortDescription: "Видеорегистратор с ночной съемкой.",
			Image:            "https://loremflickr.com/320/240?lock=19",
			URL:              "/catalog/product/20",
			Currency:         "$",
		},
	},
}
