env: local

main_service:
  domain: "main_go"
  address: "0.0.0.0"
  port: "8000"

rating_updater:
  domain: "rating_updater_go"
  address: "0.0.0.0"
  port: "8004"

profile_go:
  domain: "profile_go"
  address: "0.0.0.0"
  port: "8003"

user_go:
  domain: "user_go"
  address: "0.0.0.0"
  port: "8001"

wishlists_go:
  domain: "wishlists_go"
  address: "0.0.0.0"
  port: "8006"

mongo_db:
  domain: "mongo_db"
  port: "27017"
  address: "0.0.0.0"


notifications_go:
  domain: "notifications_go"
  address: "0.0.0.0"
  port: "8006"

promocodes_go:
  domain: "promocodes_go"
  address: "0.0.0.0"
  port: "8005"

kafka:
  domain: "kafka"
  port: "9092"