// Code generated by MockGen. DO NOT EDIT.
// Source: init.go
//
// Generated by this command:
//
//	mockgen -source=init.go -destination=mocks/mockgen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/go-park-mail-ru/2024_2_kotyari/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockreviewsRepo is a mock of reviewsRepo interface.
type MockreviewsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockreviewsRepoMockRecorder
	isgomock struct{}
}

// MockreviewsRepoMockRecorder is the mock recorder for MockreviewsRepo.
type MockreviewsRepoMockRecorder struct {
	mock *MockreviewsRepo
}

// NewMockreviewsRepo creates a new mock instance.
func NewMockreviewsRepo(ctrl *gomock.Controller) *MockreviewsRepo {
	mock := &MockreviewsRepo{ctrl: ctrl}
	mock.recorder = &MockreviewsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreviewsRepo) EXPECT() *MockreviewsRepoMockRecorder {
	return m.recorder
}

// AddReview mocks base method.
func (m *MockreviewsRepo) AddReview(ctx context.Context, productID, userID uint32, review model.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReview", ctx, productID, userID, review)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReview indicates an expected call of AddReview.
func (mr *MockreviewsRepoMockRecorder) AddReview(ctx, productID, userID, review any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReview", reflect.TypeOf((*MockreviewsRepo)(nil).AddReview), ctx, productID, userID, review)
}

// DeleteReview mocks base method.
func (m *MockreviewsRepo) DeleteReview(ctx context.Context, productID, userID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReview", ctx, productID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReview indicates an expected call of DeleteReview.
func (mr *MockreviewsRepoMockRecorder) DeleteReview(ctx, productID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReview", reflect.TypeOf((*MockreviewsRepo)(nil).DeleteReview), ctx, productID, userID)
}

// GetProductReviews mocks base method.
func (m *MockreviewsRepo) GetProductReviews(ctx context.Context, productID uint32) (model.Reviews, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductReviews", ctx, productID)
	ret0, _ := ret[0].(model.Reviews)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductReviews indicates an expected call of GetProductReviews.
func (mr *MockreviewsRepoMockRecorder) GetProductReviews(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductReviews", reflect.TypeOf((*MockreviewsRepo)(nil).GetProductReviews), ctx, productID)
}

// GetReview mocks base method.
func (m *MockreviewsRepo) GetReview(ctx context.Context, productID, userID uint32) (model.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReview", ctx, productID, userID)
	ret0, _ := ret[0].(model.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReview indicates an expected call of GetReview.
func (mr *MockreviewsRepoMockRecorder) GetReview(ctx, productID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReview", reflect.TypeOf((*MockreviewsRepo)(nil).GetReview), ctx, productID, userID)
}

// UpdateReview mocks base method.
func (m *MockreviewsRepo) UpdateReview(ctx context.Context, productID, userID uint32, review model.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReview", ctx, productID, userID, review)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReview indicates an expected call of UpdateReview.
func (mr *MockreviewsRepoMockRecorder) UpdateReview(ctx, productID, userID, review any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReview", reflect.TypeOf((*MockreviewsRepo)(nil).UpdateReview), ctx, productID, userID, review)
}
