basePath: /
definitions:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
host: oxic.swagger.io
info:
  contact: {}
  title: Swagger Oxic API
paths:
    post:
      consumes:
      - application/json
      parameters:
        in: body
        required: true
        schema:
      produces:
      - application/json
      responses:
        "200":
          schema:
            type: string
        "400":
          schema:
          schema:
        "500":
          schema:
      tags:
      - auth
swagger: "2.0"
