package db

// Инициализация продуктов в базе данных
var productsData = map[string]Product{
	"1": {
		CurrentPrice:     "2473",
		OldPrice:         "7632",
		Discount:         "77",
		Image:            "https://ir-2.ozone.ru/s3/multimedia-1-t/wc1000/7064415605.jpg",
		Description:      "Кроссовки ASICS Модная обувь.",
		ShortDescription: "Кроссовки ASICS.",
		URL:              "/catalog/product/1",
		Currency:         "Р",
	},
	"2": {
		CurrentPrice:     "8099",
		OldPrice:         "14990",
		Discount:         "46",
		Description:      "Lydsto Робот-пылесос G1, белый.",
		ShortDescription: "Lydsto Робот-пылесос G1, белый.",
		Image:            "https://ir-2.ozone.ru/s3/multimedia-1-v/wc1000/7126624639.jpg",
		URL:              "/catalog/product/2",
		Currency:         "$",
	},
	"3": {
		CurrentPrice:     "31 513",
		Description:      "Посудомоечная машина встраиваемая Kuppersberg GSM 4574 (Модификация 2024 года).",
		ShortDescription: "Посудомоечная машина встраиваемая.",
		Image:            "https://ir.ozone.ru/s3/multimedia-1-l/wc1000/6945183741.jpg",
		URL:              "/catalog/product/3",
		Currency:         "$",
	},
	"4": {
		CurrentPrice:     "7999",
		Description:      "Капсулы для стирки Персил Power Caps Color 4в1, 14 шт х 4 упаковки, 56 шт, для цветного белья.",
		ShortDescription: "Капсулы для стирки Персил Power Caps Color 4в1, 14 шт х 4 упаковки, 56 шт, для цветного белья.",
		Image:            "https://ir.ozone.ru/s3/multimedia-1-3/wc1000/7122182283.jpg",
		URL:              "/catalog/product/4",
		Currency:         "$",
	},
	"5": {
		CurrentPrice:     "127 977",
		OldPrice:         "174 444",
		Discount:         "30",
		Description:      "Vivo Смартфон X100 Ultra CN 16/512 ГБ, черный.",
		ShortDescription: "Vivo Смартфон X100 Ultra CN 16/512 ГБ, черный.",
		Image:            "https://ir.ozone.ru/s3/multimedia-1-n/wc1000/7036498211.jpg",
		URL:              "/catalog/product/5",
		Currency:         "$",
	},
	"6": {
		CurrentPrice:     "12999",
		Description:      "Лонгслив Cave",
		ShortDescription: "Лонгслив Cave",
		Image:            "https://ir.ozone.ru/s3/multimedia-1-4/wc1000/7128660136.jpg",
		URL:              "/catalog/product/6",
		Currency:         "$",
	},
	"7": {
		CurrentPrice:     "999",
		Description:      "Кабель для зарядки USB-C длиной 1.5 метра.",
		ShortDescription: "Кабель для зарядки USB-C, 1.5 метра.",
		Image:            "https://loremflickr.com/320/240?lock=6",
		URL:              "/catalog/product/7",
		Currency:         "$",
	},
	"8": {
		CurrentPrice:     "344",
		OldPrice:         "572",
		Discount:         "39",
		Description:      "Туалетная бумага Papia Bali flower белая 3 слоя 12 рулонов",
		ShortDescription: "Туалетная бумага Papia Bali flower белая 3 слоя 12 рулонов",
		Image:            "https://loremflickr.com/320/240?lock=7",
		URL:              "/catalog/product/8",
		Currency:         "$",
	},
	"9": {
		CurrentPrice:     "19999",
		OldPrice:         "24999",
		Discount:         "20",
		Description:      "Ноутбук с процессором i7 и SSD на 512 ГБ.",
		ShortDescription: "Ноутбук i7, SSD 512 ГБ.",
		Image:            "https://loremflickr.com/320/240?lock=8",
		URL:              "/catalog/product/9",
		Currency:         "$",
	},
	"10": {
		CurrentPrice:     "799",
		Description:      "Чехол для смартфона из мягкого силикона.",
		ShortDescription: "Чехол для смартфона, силикон.",
		Image:            "https://loremflickr.com/320/240?lock=9",
		URL:              "/catalog/product/10",
		Currency:         "$",
	},
	"11": {
		CurrentPrice:     "11999",
		Description:      "Зеркальная камера с разрешением 24 МП и объективом 18-55 мм.",
		ShortDescription: "Зеркальная камера 24 МП.",
		Image:            "https://loremflickr.com/320/240?lock=10",
		URL:              "/catalog/product/11",
		Currency:         "$",
	},
	"12": {
		CurrentPrice:     "2999",
		Description:      "Портативный Bluetooth-динамик с водонепроницаемым корпусом.",
		ShortDescription: "Bluetooth-динамик, водонепроницаемый.",
		Image:            "https://loremflickr.com/320/240?lock=11",
		URL:              "/catalog/product/12",
		Currency:         "$",
	},
	"13": {
		CurrentPrice:     "49999",
		Description:      "Игровая консоль с поддержкой 4K и встроенным SSD.",
		ShortDescription: "Игровая консоль, 4K, SSD.",
		Image:            "https://loremflickr.com/320/240?lock=12",
		URL:              "/catalog/product/13",
		Currency:         "$",
	},
	"14": {
		CurrentPrice:     "1199",
		Description:      "Микрофон для записи подкастов и стримов.",
		ShortDescription: "Микрофон для подкастов и стримов.",
		Image:            "https://loremflickr.com/320/240?lock=13",
		URL:              "/catalog/product/14",
		Currency:         "$",
	},
	"15": {
		CurrentPrice:     "3499",
		Description:      "Геймпад с поддержкой Bluetooth для ПК и консолей.",
		ShortDescription: "Геймпад Bluetooth для ПК и консолей.",
		Image:            "https://loremflickr.com/320/240?lock=14",
		URL:              "/catalog/product/15",
		Currency:         "$",
	},
	"16": {
		CurrentPrice:     "2299",
		Description:      "Внешний аккумулятор на 10000 мАч с быстрой зарядкой.",
		ShortDescription: "Внешний аккумулятор 10000 мАч.",
		Image:            "https://loremflickr.com/320/240?lock=15",
		URL:              "/catalog/product/16",
		Currency:         "$",
	},
	"17": {
		CurrentPrice:     "19999",
		Description:      "Проектор для домашнего кинотеатра с поддержкой Full HD.",
		ShortDescription: "Проектор для кинотеатра, Full HD.",
		Image:            "https://loremflickr.com/320/240?lock=16",
		URL:              "/catalog/product/17",
		Currency:         "$",
	},
	"18": {
		CurrentPrice:     "34999",
		Description:      "Графический планшет с 8192 уровнями нажатия и стилусом.",
		ShortDescription: "Графический планшет со стилусом.",
		Image:            "https://loremflickr.com/320/240?lock=17",
		URL:              "/catalog/product/18",
		Currency:         "$",
	},
	"19": {
		CurrentPrice:     "9999",
		Description:      "Очки виртуальной реальности с поддержкой 4K.",
		ShortDescription: "Очки виртуальной реальности 4K.",
		Image:            "https://loremflickr.com/320/240?lock=18",
		URL:              "/catalog/product/19",
		Currency:         "$",
	},
	"20": {
		CurrentPrice:     "7499",
		Description:      "Видеорегистратор с ночной съемкой и GPS.",
		ShortDescription: "Видеорегистратор с ночной съемкой.",
		Image:            "https://loremflickr.com/320/240?lock=19",
		URL:              "/catalog/product/20",
		Currency:         "$",
	},
}

var usersData = map[string]User{
	"user@example.com": {
		Username: "Goshanchik",
		Password: "Password123@",
	},
	"user1@example.com": {
		Username: "Igorechik",
		Password: "Password124@",
	},
}
